FROM golang:1.25-alpine AS build
WORKDIR /app
RUN apk add --no-cache bash ca-certificates
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o server ./cmd/server

FROM alpine:3.19
WORKDIR /app
COPY --from=build /app/server /app/server
COPY --from=build /app/migrations /app/migrations
EXPOSE 5173
CMD ["/app/server"]

